# https://github.com/prefix-dev/pixi/pull/1493
exclude: |
  (?x)
  ^\.pixi/
  | ^pixi\.lock$
repos:
  - repo: local
    hooks:
      - id: pixi-install
        name: pixi-install
        entry: pixi install -e lint
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
      - id: ruff-check
        name: ruff
        entry: pixi run -e lint ruff check --exit-non-zero-on-fix --fix --force-exclude
        language: system
        files: ^(src|tests)/
        types_or: [python, pyi]
        require_serial: true
        verbose: true
      - id: ruff-format
        name: ruff-format
        entry: pixi run -e lint ruff format --force-exclude
        language: system
        files: ^(src|tests)/
        types_or: [python, pyi]
        require_serial: true
        verbose: true
