name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.62.2
          cache: true

      - name: Build package
        run: pixi run -e build build

      - name: Test package
        run: pixi run -e py312 test

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
